name: Update v1.xml
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Download the latest v1.xml
        run: curl https://edge.microsoft.com/neededge/v1 > v1.xml
      - name: Diff
        run: git diff --exit-code || echo "::set-output name=DIFF_EXISTS::1"
        id: diff
      - if: steps.diff.outputs.DIFF_EXISTS
        name: Push the latest
        run: |
          DATE=$(date '+%Y-%m-%d')
          # BRANCH=update-${DATE}
          BRANCH=master
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "github-actions-bot@users.noreply.github.com"
          # git checkout -b "$BRANCH"
          git add v1.xml
          git commit -m "update v1.xml to the latest on ${DATE}"
          git push -u origin "$BRANCH"
